### ISSUE TITLE
Issue with rendering React when using the browser back button

### ISSUE THREAD

**Issue by nanorepublica** [Frojd/django-react-templatetags#62]
Hi there, 

Firstly thanks for this project! It has enabled me to start shifting to start adding React to my codebase incrementally which is amazing!

Disclaimer: This issue could be down to the particular code base I am working on. It is using this library which looks to mess with the state of the back button (https://github.com/defunkt/jquery-pjax)

This issue can be reproduced as follows: 

1. Go to a page which uses this library
2. Then navigate to another page
3. Then use the browser back button
4. If at this point you inspect the elements the uuid in the data/javascript is different from the uuid in the HTML id of the div where the React should render. 

Screen recording: https://www.loom.com/share/5247e399ace045ee82d3744b009d6b1bx

Workaround: just use the identifier argument in the `react_render` template tag.

**Comment by marteinn** [comment]
Hi @nanorepublica and thanks for the bug report! I noticed in your screen recording (much appreciated btw) that you are using PJAX and my first guess is that PJAX does not use the old "script" tag from previous state.

We have used DRTT with both Turbolinks and PJAX in the past so it should work, but both PJAX/Turbolinks needs some configuration to behave correctly.  I'm pretty sure the issue is with PJAX here.

So please take another look at your PJAX configuration and also verify that your project works without it. If you are still having issues just report back here, I will keep the issue open.

Cheers!

**Comment by nanorepublica** [comment]
Thanks for the quick response. I will have a look at my PJAX config and get back to you. Pretty sure that it will be the issue from what I can tell.

**Comment by marteinn** [comment]
👍 Same here, I think the issue is the custom script tags that DRTT are mismatched due to PJAX state restore. The solution is probably to make sure PJAX includes those script tags as well.

Good luck!

**Comment by marteinn** [comment]
I'm closing this issue now due to inactivity and that it is most likely unrelated to DRTT.
